<?php
class Migration_Category_data extends CI_Migration {

	public function up()
	{
		$this->load->database();
		$data = array(
			array("kode"=>"1.3", "nama"=>"ASET TETAP", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.1", "nama"=>"Tanah", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.1.1", "nama"=>"Tanah", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.2", "nama"=>"Peralatan dan Mesin", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.2.1", "nama"=>"Alat-Alat Besar Darat", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.2.10", "nama"=>"Alat Bengkel Tak Bermesin", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.11", "nama"=>"Alat Ukur", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.12", "nama"=>"Alat Pengolahan Pertanian", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.13", "nama"=>"Alat Pemeliharaan Tanaman/Alat Penyimpan Pertanian", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.14", "nama"=>"Alat Kantor", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.15", "nama"=>"Alat Rumah Tangga", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.16", "nama"=>"Peralatan Komputer", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.17", "nama"=>"Meja dan Kursi Kerja/Rapat Pejabat", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.18", "nama"=>"Alat Studio", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"1000000", "deleted"=>0),
			array("kode"=>"1.3.2.19", "nama"=>"Alat Komunikasi", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.2", "nama"=>"Alat-Alat Besar Apung", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.2.20", "nama"=>"Peralatan Pemancar", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.21", "nama"=>"Alat Kedokteran", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"750000", "deleted"=>0),
			array("kode"=>"1.3.2.22", "nama"=>"Alat Kesehatan", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"750000", "deleted"=>0),
			array("kode"=>"1.3.2.23", "nama"=>"Unit-Unit Laboratorium", "umur_ekonomis"=>"8", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.24", "nama"=>"Alat Peraga/Praktek Sekolah", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.25", "nama"=>"Unit Alat Laboratorium Kimia Nuklir", "umur_ekonomis"=>"15", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.26", "nama"=>"Alat Laboratorium Fisika Nuklir / Elektronika", "umur_ekonomis"=>"15", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.27", "nama"=>"Alat Proteksi Radiasi / Proteksi Lingkungan", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.28", "nama"=>"Radiation Aplication and Non Destructive Testing Laboratory (BATAM)", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.29", "nama"=>"Alat Laboratorium Lingkungan Hidup", "umur_ekonomis"=>"7", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.3", "nama"=>"Alat-alat Bantu", "umur_ekonomis"=>"7", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.30", "nama"=>"Peralatan Laboratorium Hidrodinamika", "umur_ekonomis"=>"15", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.31", "nama"=>"Senjata Api", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.32", "nama"=>"Persenjataan Non Senjata Api", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.33", "nama"=>"Alat Keamanan dan Perlindungan", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.2.4", "nama"=>"Alat Angkutan Darat Bermotor", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"2000000", "deleted"=>0),
			array("kode"=>"1.3.2.5", "nama"=>"Alat Angkutan Berat Tak Bermotor", "umur_ekonomis"=>"2", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.6", "nama"=>"Alat Angkut Apung Bermotor", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"1500000", "deleted"=>0),
			array("kode"=>"1.3.2.7", "nama"=>"Alat Angkut Apung Tak Bermotor", "umur_ekonomis"=>"3", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.2.8", "nama"=>"Alat Angkut Bermotor Udara", "umur_ekonomis"=>"20", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.2.9", "nama"=>"Alat Bengkel Bermesin", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"300000", "deleted"=>0),
			array("kode"=>"1.3.3", "nama"=>"Gedung dan Bangunan", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.3.1", "nama"=>"Bangunan Gedung Tempat Kerja", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.10", "nama"=>"Rambu-Rambu", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.3.11", "nama"=>"Rambu-Rambu Lalu Lintas Udara", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"5000000", "deleted"=>0),
			array("kode"=>"1.3.3.2", "nama"=>"Bangunan Gedung Tempat Tinggal", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.3", "nama"=>"Bangunan Menara", "umur_ekonomis"=>"20", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.4", "nama"=>"Bangunan Bersejarah", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.5", "nama"=>"Tugu Peringatan", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.6", "nama"=>"Candi", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.7", "nama"=>"Monumen/Bangunan Bersejarah", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.8", "nama"=>"Tugu Peringatan Lain", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.3.9", "nama"=>"Tugu Titik Kontrol/Pasti", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4", "nama"=>"Jalan, Irigasi, dan Jaringan", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.4.1", "nama"=>"Jalan", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.10", "nama"=>"Bangunan Air", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.11", "nama"=>"Instalasi Air Minum/Air Bersih", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.12", "nama"=>"Instalasi Air Kotor", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.13", "nama"=>"Instalasi Pengolahan Sampah Organik dan Non Organik", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.14", "nama"=>"Instalasi Pengolahan Bahan Bangunan", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.15", "nama"=>"Instalasi Pembangkit Listrik", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.16", "nama"=>"Instalasi Gardu Listrik", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.17", "nama"=>"Instalasi Pertahanan", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.18", "nama"=>"Instalasi Gas", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.19", "nama"=>"Instalasi Pengaman", "umur_ekonomis"=>"20", "batas_kapitalisasi"=>"5000000", "deleted"=>0),
			array("kode"=>"1.3.4.2", "nama"=>"Jembatan", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.20", "nama"=>"Jaringan Air Minum", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.21", "nama"=>"Jaringan Listrik", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"2500000", "deleted"=>0),
			array("kode"=>"1.3.4.22", "nama"=>"Jaringan Telepon", "umur_ekonomis"=>"20", "batas_kapitalisasi"=>"2000000", "deleted"=>0),
			array("kode"=>"1.3.4.23", "nama"=>"Jaringan Gas", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.3", "nama"=>"Bangunan Air Irigasi", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.4", "nama"=>"Bangunan Air Pasang Surut", "umur_ekonomis"=>"50", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.5", "nama"=>"Bangunan Air Rawa", "umur_ekonomis"=>"25", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.6", "nama"=>"Bangunan Pengaman Sungai dan Penanggulangan Bencana Alam", "umur_ekonomis"=>"10", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.7", "nama"=>"Bangunan Pengembangan Sumber Air dan Air Tanah", "umur_ekonomis"=>"30", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.8", "nama"=>"Bangunan Air Bersih/Baku", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.4.9", "nama"=>"Bangunan Air Kotor", "umur_ekonomis"=>"40", "batas_kapitalisasi"=>"10000000", "deleted"=>0),
			array("kode"=>"1.3.5", "nama"=>"Aset Tetap Lainnya", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.5.1", "nama"=>"Buku", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"100000", "deleted"=>0),
			array("kode"=>"1.3.5.2", "nama"=>"Terbitan", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"100000", "deleted"=>0),
			array("kode"=>"1.3.5.3", "nama"=>"Barang-Barang Perpustakaan", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"100000", "deleted"=>0),
			array("kode"=>"1.3.5.4", "nama"=>"Barang Bercorak Kebudayaan", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.5.5", "nama"=>"Alat Olah Raga Lainnya", "umur_ekonomis"=>"4", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.5.6", "nama"=>"Hewan", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"500000", "deleted"=>0),
			array("kode"=>"1.3.5.7", "nama"=>"Tanaman", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"250000", "deleted"=>0),
			array("kode"=>"1.3.6", "nama"=>"Kontruksi Dalam Pengerjaan", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.6.1", "nama"=>"Kontruksi Dalam Pengerjaan", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.7", "nama"=>"Aset Lainnya", "umur_ekonomis"=>"0", "batas_kapitalisasi"=>"0", "deleted"=>0),
			array("kode"=>"1.3.7.1", "nama"=>"Aset Lainnya", "umur_ekonomis"=>"5", "batas_kapitalisasi"=>"0", "deleted"=>0)
		);

		$this->db->insert_batch("categories", $data);
	}

	public function down()
	{
		$this->db->truncate("categories");
	}
}