<?php
class Migration_Umur_ekonomis_data extends CI_Migration {

	public function up()
	{
		$this->load->database();
		$data = array(
			array("kode_kategori"=>"1.3.3.10", "uraian"=>"Rambu-rambu Lalu Lintas Darat", "awal"=>"0", "akhir"=>"25", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.10", "uraian"=>"Rambu-rambu Lalu Lintas Darat", "awal"=>"25", "akhir"=>"50", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.10", "uraian"=>"Rambu-rambu Lalu Lintas Darat", "awal"=>"50", "akhir"=>"75", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.10", "uraian"=>"Rambu-rambu Lalu Lintas Darat", "awal"=>"75", "akhir"=>"100", "tahun"=>"4", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.11", "uraian"=>"Rambu-rambu Lalu Lintas Udara", "awal"=>"0", "akhir"=>"25", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.11", "uraian"=>"Rambu-rambu Lalu Lintas Udara", "awal"=>"25", "akhir"=>"75", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.11", "uraian"=>"Rambu-rambu Lalu Lintas Udara", "awal"=>"75", "akhir"=>"100", "tahun"=>"4", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.1", "uraian"=>"Bangunan Gedung Tempat Kerja", "awal"=>"0", "akhir"=>"25", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.1", "uraian"=>"Bangunan Gedung Tempat Kerja", "awal"=>"25", "akhir"=>"50", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.1", "uraian"=>"Bangunan Gedung Tempat Kerja", "awal"=>"50", "akhir"=>"75", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.1", "uraian"=>"Bangunan Gedung Tempat Kerja", "awal"=>"75", "akhir"=>"100", "tahun"=>"50", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.2", "uraian"=>"Bangunan Gedung Tempat Tinggal", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.2", "uraian"=>"Bangunan Gedung Tempat Tinggal", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.2", "uraian"=>"Bangunan Gedung Tempat Tinggal", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.6", "uraian"=>"Candi/Tugu Peringatan/Prasasti", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.6", "uraian"=>"Candi/Tugu Peringatan/Prasasti", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.6", "uraian"=>"Candi/Tugu Peringatan/Prasasti", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.3", "uraian"=>"Bangunan Menara Perambuan", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.3", "uraian"=>"Bangunan Menara Perambuan", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.3", "uraian"=>"Bangunan Menara Perambuan", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.9", "uraian"=>"Tugu Titik Kontrol/Prasasti Tugu/Tanda Batas", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.9", "uraian"=>"Tugu Titik Kontrol/Prasasti Tugu/Tanda Batas", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.3.9", "uraian"=>"Tugu Titik Kontrol/Prasasti Tugu/Tanda Batas", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.1", "uraian"=>"Jalan", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.1", "uraian"=>"Jalan", "awal"=>"30", "akhir"=>"60", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.1", "uraian"=>"Jalan", "awal"=>"60", "akhir"=>"100", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.2", "uraian"=>"Jembatan", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.2", "uraian"=>"Jembatan", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.2", "uraian"=>"Jembatan", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.3", "uraian"=>"Bangunan Air Irigasi", "awal"=>"0", "akhir"=>"5", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.3", "uraian"=>"Bangunan Air Irigasi", "awal"=>"5", "akhir"=>"10", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.3", "uraian"=>"Bangunan Air Irigasi", "awal"=>"10", "akhir"=>"20", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.4", "uraian"=>"Bangunan Pengairan Pasang Surut", "awal"=>"0", "akhir"=>"5", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.4", "uraian"=>"Bangunan Pengairan Pasang Surut", "awal"=>"5", "akhir"=>"10", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.4", "uraian"=>"Bangunan Pengairan Pasang Surut", "awal"=>"10", "akhir"=>"20", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.5", "uraian"=>"Bangunan Pengembangan Rawa dan Polder", "awal"=>"0", "akhir"=>"5", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.5", "uraian"=>"Bangunan Pengembangan Rawa dan Polder", "awal"=>"5", "akhir"=>"10", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.5", "uraian"=>"Bangunan Pengembangan Rawa dan Polder", "awal"=>"10", "akhir"=>"20", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.6", "uraian"=>"Bangunan Pengaman Sungai/Pantai & Penanggulangan Bencana", "awal"=>"0", "akhir"=>"5", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.6", "uraian"=>"Bangunan Pengaman Sungai/Pantai & Penanggulangan Bencana", "awal"=>"5", "akhir"=>"10", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.6", "uraian"=>"Bangunan Pengaman Sungai/Pantai & Penanggulangan Bencana", "awal"=>"10", "akhir"=>"20", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.7", "uraian"=>"Bangunan Pengembangan Sumber Air dan Tanah", "awal"=>"0", "akhir"=>"5", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.7", "uraian"=>"Bangunan Pengembangan Sumber Air dan Tanah", "awal"=>"5", "akhir"=>"10", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.7", "uraian"=>"Bangunan Pengembangan Sumber Air dan Tanah", "awal"=>"10", "akhir"=>"20", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.8", "uraian"=>"Bangunan Air Bersih/Air Baku", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.8", "uraian"=>"Bangunan Air Bersih/Air Baku", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.8", "uraian"=>"Bangunan Air Bersih/Air Baku", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.9", "uraian"=>"Bangunan Air Kotor", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.9", "uraian"=>"Bangunan Air Kotor", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.9", "uraian"=>"Bangunan Air Kotor", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.11", "uraian"=>"Instalasi Air Bersih/Air Minum", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.11", "uraian"=>"Instalasi Air Bersih/Air Minum", "awal"=>"30", "akhir"=>"45", "tahun"=>"7", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.11", "uraian"=>"Instalasi Air Bersih/Air Minum", "awal"=>"45", "akhir"=>"65", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.12", "uraian"=>"Instalasi Air Kotor", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.12", "uraian"=>"Instalasi Air Kotor", "awal"=>"30", "akhir"=>"45", "tahun"=>"7", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.12", "uraian"=>"Instalasi Air Kotor", "awal"=>"45", "akhir"=>"65", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.13", "uraian"=>"Instalasi Pengolahan Sampah", "awal"=>"0", "akhir"=>"30", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.13", "uraian"=>"Instalasi Pengolahan Sampah", "awal"=>"30", "akhir"=>"45", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.13", "uraian"=>"Instalasi Pengolahan Sampah", "awal"=>"45", "akhir"=>"65", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.14", "uraian"=>"Instalasi Pengolahan Bahan Bangunan", "awal"=>"0", "akhir"=>"30", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.14", "uraian"=>"Instalasi Pengolahan Bahan Bangunan", "awal"=>"30", "akhir"=>"45", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.14", "uraian"=>"Instalasi Pengolahan Bahan Bangunan", "awal"=>"45", "akhir"=>"65", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.15", "uraian"=>"Instalasi Pembangkit Listrik", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.15", "uraian"=>"Instalasi Pembangkit Listrik", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.15", "uraian"=>"Instalasi Pembangkit Listrik", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.16", "uraian"=>"Instalasi Gardu Listrik", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.16", "uraian"=>"Instalasi Gardu Listrik", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.16", "uraian"=>"Instalasi Gardu Listrik", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.17", "uraian"=>"Instalasi Pertahanan", "awal"=>"0", "akhir"=>"30", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.17", "uraian"=>"Instalasi Pertahanan", "awal"=>"30", "akhir"=>"45", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.17", "uraian"=>"Instalasi Pertahanan", "awal"=>"45", "akhir"=>"65", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.18", "uraian"=>"Instalasi Gas", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.18", "uraian"=>"Instalasi Gas", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.18", "uraian"=>"Instalasi Gas", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.19", "uraian"=>"Instalasi Pengaman", "awal"=>"0", "akhir"=>"30", "tahun"=>"1", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.19", "uraian"=>"Instalasi Pengaman", "awal"=>"30", "akhir"=>"45", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.19", "uraian"=>"Instalasi Pengaman", "awal"=>"45", "akhir"=>"65", "tahun"=>"3", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.20", "uraian"=>"Jaringan Air Minum", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.20", "uraian"=>"Jaringan Air Minum", "awal"=>"30", "akhir"=>"45", "tahun"=>"7", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.20", "uraian"=>"Jaringan Air Minum", "awal"=>"45", "akhir"=>"65", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.21", "uraian"=>"Jaringan Listrik", "awal"=>"0", "akhir"=>"30", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.21", "uraian"=>"Jaringan Listrik", "awal"=>"30", "akhir"=>"45", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.21", "uraian"=>"Jaringan Listrik", "awal"=>"45", "akhir"=>"65", "tahun"=>"15", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.22", "uraian"=>"Jaringan Telepon", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.22", "uraian"=>"Jaringan Telepon", "awal"=>"30", "akhir"=>"45", "tahun"=>"5", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.22", "uraian"=>"Jaringan Telepon", "awal"=>"45", "akhir"=>"65", "tahun"=>"10", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.23", "uraian"=>"Jaringan Gas", "awal"=>"0", "akhir"=>"30", "tahun"=>"2", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.23", "uraian"=>"Jaringan Gas", "awal"=>"30", "akhir"=>"45", "tahun"=>"7", "deleted"=>0),
			array("kode_kategori"=>"1.3.4.23", "uraian"=>"Jaringan Gas", "awal"=>"45", "akhir"=>"65", "tahun"=>"10", "deleted"=>0)
			);

		$this->db->insert_batch("umur_ekonomis", $data);
	}

	public function down()
	{
		$this->db->truncate("umur_ekonomis");
	}
}